baraja = ["As de Corazones", "Rey de Espadas", "Reina de Tréboles"]
repartidor = iter(baraja)
print("¡Comienza el juego!")
carta1 = next(repartidor)
print("Primera carta:")
print(carta1)
carta2 = next(repartidor)
print("Segunda carta:")
print(carta2)
print("La última carta se queda oculta.")
